bersamore/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings as sett
from bersamore.views import search, index, logout_usr, user_browse, beer_browse
from tasting.api import untappd_callback
from tasting.views import (profile, settings, checkins, checkin_view,)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cellar/', include('cellar.urls')),
    url(r'^tasting/', include('tasting.urls')),
    url(r'^imports/', include('imports.urls')),
    url(r'^$', index),
    url(r'^logout/$', logout_usr),
    #url(r'^profile/$', profile),
    url(r'^checkins/$', checkins),
    url(r'^settings/$', settings),
    url(r'^checkin/(?P<beer_id>\d+)/$', checkin_view),

    url(r'^api/callback/$', untappd_callback),
    url(r'^users/$', user_browse),
    url(r'^beers/$', beer_browse),
    url(r'^profile/$', profile),
    url(r'^search/$', search),
]

cellar/urls.py
from cellar.views import beerfinder, brewery_view, style_view, beer_view

__author__ = 'steffe'

from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^beer/(?P<beer_id>\d+)/$', beer_view),
    url(r'^beerfinder/$', beerfinder),
    url(r'^brewery/(?P<brewery_id>\d+)/$', brewery_view),
    url(r'^style/(?P<style_id>\d+)/$', style_view),
]

tasting/urls.py
from tasting.api import get_systembolaget_cookies
from tasting.views import tasting_checkin_view, stats_view, checkin_overview, baseview, tastestats
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^checkin/(?P<tasting_id>\d+)/(?P<beer_i>\d+)/$', tasting_checkin_view),
    url(r'^checkin/(?P<tasting_id>\d+)/$', tasting_checkin_view),
    url(r'^(?P<tasting_id>\d+)/$', baseview),
    url(r'^(?P<tasting_id>\d+)/stats/$', tastestats),
    url(r'^$', baseview),
    url(r'^(?P<tasting_id>\d+)/wrapitup/', stats_view),
    url(r'^overview/(?P<tasting_id>\d+)/$', checkin_overview),
    url(r'^api/cook/$', get_systembolaget_cookies),
]

tasting/models.py
from django.contrib.auth.models import User
from django.db import models
from cellar.models import Beer, Brewery, Style
from django.core.validators import MinValueValidator, MaxValueValidator

INVITATION_STATUSES = (
    (0, u'Invited'),
    (1, u'Accepted'),
    (2, u'Declined')
)


class County(models.Model):
    name = models.CharField(max_length=256)

    def __unicode__(self):
        return u'%s' % self.name


class City(models.Model):
    name = models.CharField(max_length=256)
    county = models.ForeignKey(County)

    def __unicode__(self):
        return u'%s %s' % (
            self.name, self.county
        )


class Store(models.Model):
    store_id = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=256)
    city = models.ForeignKey(City)
    zip_code = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u'%s %s %s' % (
            self.store_id, self.address, self.city
        )


class Login(models.Model):
    usr = models.ForeignKey(User)
    dt = models.DateTimeField(auto_now_add=True)


class Taster(models.Model):
    user = models.OneToOneField(User)
    receieve_email = models.BooleanField(default=True)
    allow_contacts = models.BooleanField(default=True)
    fav_beers = models.ManyToManyField(Beer, blank=True)
    fav_breweries = models.ManyToManyField(Brewery, blank=True)
    fav_styles = models.ManyToManyField(Style, blank=True)
    friends = models.ManyToManyField('tasting.Taster', related_name=u'tasterfriends', blank=True)
    stores = models.ManyToManyField(Store, blank=True)
    # http://systembevakningsagenten.se/api/json/1.0/inventoryForStore.json?id=1001

    sysbol_id = models.EmailField(
        null=True, blank=True,
        help_text=u'Used to connect against your systembolaget account'
    )
    allow_sysbol_fetch = models.BooleanField(
        default=False,
        help_text=u'Allow BMS to fetch your orderlists'
    )
    untappd_id = models.CharField(max_length=512, blank=True, null=True)
    untappd_token = models.CharField(max_length=512, blank=True, null=True)


    @property
    def beers(self):
        return self.fav_beers.all()

    @property
    def breweries(self):
        return self.fav_breweries.all()

    @property
    def styles(self):
        return self.fav_styles.all()

    @property
    def checkin_count(self):
        return Checkin.objects.filter(taster=self).count()

    def __unicode__(self):
        if self.user.first_name and self.user.last_name:
            return u'%s %s' % (self.user.first_name, self.user.last_name[0])
        if self.user.username:
            return self.user.username
        else:
            return u'%s' % self.user.email


class Friendship(models.Model):
    status = models.IntegerField(default=0, choices=INVITATION_STATUSES)
    inviter = models.ForeignKey(Taster, related_name=u'friend_inviter')
    receiver = models.ForeignKey(Taster, related_name=u'friend_receiver')
    date_created = models.DateTimeField(auto_now_add=True)
    date_accepted = models.DateTimeField(blank=True, null=True)

    def users(self):
        return Taster.objects.filter(id__in=[self.inviter.pk, self.receiver.pk])

    def friends(self, taster):
        invs = self.filter(status=1, inviter=taster).values_list('receiver', flat=True)
        recs = self.filter(status=1, receiver=taster).values_list('inviter', flat=True)
        ids = recs+invs
        friends = Taster.objects.filter(id__in=ids)
        return friends

    class Meta:
        unique_together = ('inviter', 'receiver')
        ordering = ['-date_accepted', '-date_created']

    def __unicode__(self):
        return u'%s + %s %s' % (self.inviter, self.receiver, self.get_status_display())


class TastingSession(models.Model):
    name = models.CharField(max_length=256)
    administrators = models.ManyToManyField(Taster, related_name=u'tasting_admin')
    description = models.TextField()
    date = models.DateTimeField()
    tasters = models.ManyToManyField(Taster)
    beers = models.ManyToManyField(Beer, blank=True, through='tasting.TastingBeers')
    finished = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s %s' % (self.name, self.date.strftime('%y-%m-%d %H:%M'))

    @property
    def ordered_beers(self):
        return [beer.beer for beer in self.tastingbeers_set.order_by(u'position')]

    def participating_tasters(self):
        return [t for t in self.tastinginvitation_set.all() if t.status == INVITATION_STATUSES[1]]


class TastingBeers(models.Model):
    beer = models.ForeignKey(Beer)
    tasting = models.ForeignKey(TastingSession)
    position = models.PositiveIntegerField(default=0)
    # TODO
    # description = models.TextField(blank=True, null=True, help_text=u'Overrides description from beer.')

    class Meta:
        unique_together = (u'beer', u'tasting')
        ordering = [u'position', ]


class TastingInvitation(models.Model):
    tasting = models.ForeignKey(TastingSession)
    taster = models.ForeignKey(Taster)
    status = models.IntegerField(choices=INVITATION_STATUSES, default=0)

    class Meta:
        unique_together = ('taster', 'tasting')


class Checkin(models.Model):
    taster = models.ForeignKey(Taster)
    beer = models.ForeignKey(Beer)
    date = models.DateTimeField(auto_now_add=True)
    tasting = models.ForeignKey(TastingSession, blank=True, null=True)
    from_untappd = models.BooleanField(default=False)
    pushed_to_untapppd =models.BooleanField(default=False)
    untappd_id = models.IntegerField(null=True, blank=True)

    looks = models.IntegerField(
        blank=True, null=True, validators=[
            MinValueValidator(1),
            MaxValueValidator(10)
        ]
    )
    nose = models.IntegerField(
        blank=True, null=True, validators=[
            MinValueValidator(1),
            MaxValueValidator(10)
        ]
    )
    taste = models.IntegerField(
        blank=True, null=True, validators=[
            MinValueValidator(1),
            MaxValueValidator(10)
        ]
    )
    overall = models.IntegerField(
        blank=True, null=True, validators=[
            MinValueValidator(1),
            MaxValueValidator(10)
        ]
    )

    notes = models.TextField(blank=True, null=True, max_length=300)

    def __unicode__(self):
        return u'%s %s %s (%s)' % (self.taster, self.beer, self.tasting, self.overall)

    def save(self, *args, **kwargs):
        super(Checkin, self).save(*args, **kwargs)
        beer = self.beer
        beer.recalculate()

tasting/templates/base.html
<html>
    <head>
        {% block style  %}
            <link rel="stylesheet" href="http://bsg.ddns.net/static/bootstrap/css/bootstrap-theme.css">
            <link rel="stylesheet" href="http://bsg.ddns.net/static/bootstrap/css/bootstrap.css">
        {% endblock style %}

        {%  block script %}
            <script src="http://bsg.ddns.net/static/bootstrap/js/bootstrap.js"></script>
            <script src="http://bsg.ddns.net/static/js/jquery.js"></script>
{#            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>#}

            <script>
            </script>
        {%  endblock %}
    <title>The BeerMS</title>

    <style>
        #top{
            width: 100%;
            height: 50px;
            position: fixed;
            left: 0;
            top:0;
            background-color: darkgrey;
            text-align: center;
            color: whitesmoke;
            text-shadow: 2px 2px 2px #000;
            font-size: 2.5em;
            font-weight: 600;
        }
        #menu{
            width: 100%;
            height: 50px;
            position: fixed;
            left: 0;
            top:50px;
            background-color: white;
{#            border-bottom: solid 2px darkorange;#}
{#            box-shadow: 2px 2px orange;#}
            text-align: center;
            color: whitesmoke;
{#            text-shadow: 2px 2px 2px #000;#}
            border-bottom: solid 8px darkgray;
        }

        #profile_menu{
            color: #222222;
            height: 50px;
            width:100%;
        }
        .menuitem{
            margin: 0.3em;
            padding: 0.3em;
            text-decoration: none;
        }
        .menuitem:hover{
            background-color: darkgrey;
        }
        .menuitem a:link{
            text-decoration: none;
        }
        .menuitem a:hover{
            text-decoration: none;
        }
        .submenu{
            display: none;
        }
        .submenu span{
            size: 0.9em;
            font-family: monospace;
            margin-left: 1em;
            padding:0.3em;
        }
        .submenu span:hover{
            background-color: darkgrey;
        }

        .menuspan{
            padding-left: 1.5em;
            font-weight: 900;
        }

        #menu a:link{
            text-decoration: none;
            color: whitesmoke;
            font-size:2em;
        }
        #menu a:visited{
            color: whitesmoke;
        }
        #menu a:hover{
            color: #28a4c9;
        }

        #contentblock{
            position: fixed;
            left:15%;
            width:70%;
            /*text-align: center;*/
            top: 100px;
            border-right: solid 8px darkgray;
            border-left: solid 8px darkgray;
            border-bottom: solid 8px darkgray;
            padding-left: 1em;
            padding-right: 1em;
            padding-bottom: 1em;
            /*box-shadow: 2px 2px orange;*/
        }

        html{
            background-color: lightgray;
            font-family: sans-serif;
        }
        #beer_img{
            padding-top: 1em;
            max-height: 90vh;
            max-width: 50vh;
            float: left;
            z-index: 0;
        }
        #beer_info{
            font-size: 2em;
        }
        #beer_name{
            /*position: fixed;
            right:50%;
            width:70%;
            text-align: center;*/
            top: 120px;
            color:black;
            font-size: 2.5em;
            font-weight: 600;
            text-shadow: 2px 2px 3px dimgray;

        }
        #content_wrapper{
            width: 100%;
            height: 95vh;
            background-color: white;
        }
        #beer_div{
            float:left;
            width: 100%;
        }
        #beertable{
            margin-top: 2em;
            width: 50%;
        }

        #beertable th{
            padding-right: 1.5em;
        }

        #stats_div{
/*            width: 40%;
            margin-left: 60%;*/
            margin-top: 2em;
        }
        th{
            vertical-align: top;
            text-align: left;
            padding-left: 1.5em;
        }
        td{
            padding-left: 1em;
        }
        #statstable{
            width:90%
        }
        #statstable td{
            padding: 2em;
        }
        #links{
            height: 25px;
            position: fixed;
            top: 0;
            right: 40px;
        }

        #links img{
            height: 25px;
            width: 25px;

        }
        #links a:hover{
            background-color: white;
        }
        #statsimg{
            width: 50px;
        }
        #statsimg_menu{
            height: 35px;
        }
        .stats_td{
            padding:0.4em;
        }
        .stats_th{
            padding:0.4em;
        }
        #sysbol_inline{
            height: 2em;
        }

    </style>

    </head>
    <body>

        <div id="top">
            {%  block top %}
                <div class="top_div">
                    Beer Management System [beta]
                </div>
            <div id="links">
                <a href="/profile/"><img src="http://bsg.ddns.net/static/images/home.png"></a>
                <a href="/settings/"><img src="http://bsg.ddns.net/static/images/gear.png"></a>
                <a href="/logout/"><img src="http://bsg.ddns.net/static/images/logout.png"></a>
            </div>
            {%  endblock top %}
        </div>

        <div id="menu">
            {% block menu %}
            {% endblock %}
        </div>

        <div id="contentblock">
            {%  block content %}
            {%  endblock content %}
        </div>

    {%  block bottom %}
    {%  endblock bottom %}

    </body>
</html>

tasting/templates/beer_browse.html
{% extends 'base_temp.html' %}

{%  block head %}
    {{ block.super }}
{% endblock %}

{%  block nav %}
    {{ block.super }}
{%  endblock nav %}

{%  block content %}
<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Browse Beers</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s1 m1 l1">
                {% for l in letters %}
                    <a href="?letter={{ l }}" class="thin btn">{{ l }}</a>
                {% endfor %}
            </div>

            <div class="col s11 m11 l11">
                <table>
                    <thead>
                        <tr>
                            <th data-field="id">Name</th>
                            <th data-field="id">Brewery</th>
                            <th data-field="id">Country</th>
                            <th data-field="id">IBU</th>
                            <th data-field="id">ABV</th>
                            <th data-field="id">Avg</th>
                            <th data-field="id">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                    {% for b in beers %}
                        <tr>
                            <td>{{ b.name }}</td>
                            <td>{{ b.brewery.name }}</td>
                            <td>{{ b.brewery.country.code }}</td>
                            <td>{{ b.ibu }}</td>
                            <td>{{ b.abv }}</td>
                            <td>0.0/{{ b.avg }}</td>
                            <td>[ Add to fav ] [ Add to tasting] [ Add to Bottlesharing ]</td>
                        </tr>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>
{%  endblock content %}

{% block script %}
{{ block.super }}
{% endblock script %}

tasting/templates/checkin.jinja2
<div id="checkin_header">
    <div id="tasting_info">
        Checking in @ {{ checkin.tasting.name }}
    </div>
    <div>
        {% for b in tasting.beers.all %}
            <span class="header_beer"
                    {% if b == checkin.beer %}id="active"{% endif %}>({{ forloop.counter }}) {{ b.style }}</span>
        {% endfor %}
    </div>
</div>

<div id="checkin_body">
    {{ checkin.beer.style }}

    <table>
        <tr id="criteria">
            <th colspan="2">Criteria</th>
        </tr>
        <tr>
            <th>
                Looks
            </th>
            <td>
                <select name="looks">
                    <option value="0">---</option>
                    <option value="1">1</option>
                    <option value="1">2</option>
                    <option value="1">3</option>
                    <option value="1">4</option>
                    <option value="1">5</option>
                    <option value="1">6</option>
                    <option value="1">7</option>
                    <option value="1">8</option>
                    <option value="1">9</option>
                    <option value="1">10</option>
                </select>
            </td>
        </tr>

        <tr>
            <th>
                Smell
            </th>
            <td>
                <select name="smell">
                    <option value="0">---</option>
                    <option value="1">1</option>
                    <option value="1">2</option>
                    <option value="1">3</option>
                    <option value="1">4</option>
                    <option value="1">5</option>
                    <option value="1">6</option>
                    <option value="1">7</option>
                    <option value="1">8</option>
                    <option value="1">9</option>
                    <option value="1">10</option>
                </select>
            </td>
        </tr>

        <tr>
            <th>
                Taste
            </th>
            <td>
                <select name="taste">
                    <option value="0">---</option>
                    <option value="1">1</option>
                    <option value="1">2</option>
                    <option value="1">3</option>
                    <option value="1">4</option>
                    <option value="1">5</option>
                    <option value="1">6</option>
                    <option value="1">7</option>
                    <option value="1">8</option>
                    <option value="1">9</option>
                    <option value="1">10</option>
                </select>
            </td>
        </tr>

        <tr>
            <th>
                Overall
            </th>
            <td>
                <select name="overall">
                    <option value="0">---</option>
                    <option value="1">1</option>
                    <option value="1">2</option>
                    <option value="1">3</option>
                    <option value="1">4</option>
                    <option value="1">5</option>
                    <option value="1">6</option>
                    <option value="1">7</option>
                    <option value="1">8</option>
                    <option value="1">9</option>
                    <option value="1">10</option>
                </select>
            </td>
        </tr>

        <tr>
            <th>
                Notes
            </th>
            <td>
                <textarea name="notes"></textarea>
            </td>
        </tr>

    </table>
</div>

<style>
    .header_beer{
        background-color: lightgray;
        margin: 0.5em;
    }
    #active{
        background-color: gold;
    }
    #checkin_header{
        border-bottom: solid 1px darkgrey;
        margin-bottom: 1em;
    }

    #criteria{
        padding: 0.3em;
    }
    select{
        width: 70%;
    }
    textarea{
        width: 70%;
    }
</style>

tasting/templates/new_profile.html
{% extends 'base_temp.html' %}

{%  block head %}
    {{ block.super }}
{% endblock %}

{%  block nav %}
    {{ block.super }}
{%  endblock nav %}

{%  block content %}
<div id="wrapper">
    <div class="container">

    {% if admin %}
        <div class="row">
            <div class="col s12 m12 l12">
                <h5>ADMIN stuff</h5>
                <a href="/imports/list_imports/">Imports</a><br>
            </div>
        </div>
    {% endif %}
        <div class="row">
            <div class="col s12 m12 l12">
                <h3>Profile Overview</h3>
                {%  if not logged_in %}
                    <a href="{{ untappd_login_url }}">Connect to Untappd</a>
                {% else %}
                <span style="color: deeppink; font-weight: 900">
                    Connected to untappd as <a href="https://untappd.com/user/{{ usr.taster.untappd_id }}">
                    {{ usr.taster.untappd_id }}
                    </a>
                </span>
            </div>
            <div class="col s12 m12 l12 collection">
                <div>Latest untappd-checkins</div>
                <table>
                    {%  if latest %}
                        <tr>
                            <th>Name</th>
                            <th>Brewery</th>
                            <th>Grade</th>
                        </tr>
                        {% for l in latest %}
                            <tr>
                                <td>
                                    <a href="http://untappd.com/b/{{ l.4 }}">{{ l.0 }}</a></td>
                                <td>{{ l.1 }}</td>
                                <td>{{ l.2 }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </table>
            </div>
                {% endif %}

            </div>
        </div>

    </div>

        <h3>Friends</h3>
    Latest connected friends: [
        {% for a,o in accepted.items %}
            {{ a }}{{ o.date_accepted }}
        {% endfor %}
        ]<br>
    <h4>{{ invs }}</h4>
    <h4>{{ recs }}</h4>
{#        {% for f in friends %}#}
{#            {{ f.receiver }}#}
{#        {% endfor %}#}
        <h2>Your tastings</h2>
        {%  for tasting in tastings %}
            <a href="/tasting/{{ tasting.pk }}">
                {{ tasting.name }}
            </a> {% if tasting.finished %}
                ( Finished )
                <a href="/tasting/{{ tasting.pk }}/stats/"> Your stats</a> |
                <a href="/tasting/{{ tasting.pk }}/wrapitup/"> Overall stats</a>
        {% else %}
            starts at: {{ tasting.date|date:'d/m-y H:i' }}
        {% endif %}
            <br>
        {% endfor %}

        {%  if usr.taster.checkin_set.exists %}
            <h2>Your 10 latest checkins</h2>
            <table>
            <tr>
                <th>
                    Beer
                </th>
                <th>
                    Style
                </th>
                <th>
                    Brewery
                </th>
                <th>
                    Rating
                </th>
                <th>
                    Date
                </th>
                <th>
                    Tasting
                </th>
            </tr>
            {%  for checkin in checkins %}
                <tr>
                <td>
                    <a href="/cellar/beer/{{ checkin.beer.pk }}">{{ checkin.beer.name }}</a>
                </td>
                <td>
                    <a href="/cellar/style/{{ checkin.beer.style.pk }}">{{ checkin.beer.style.name }}</a>
                </td>
                <td>
                    <a href="/cellar/brewery/{{ checkin.beer.brewery.pk }}">{{ checkin.beer.brewery }}</a>
                </td>
                <td>{{ checkin.overall }} ({{ checkin.beer.avg }})</td>
                <td>{{ checkin.date|date:'d/m-y' }}</td>
                <td>{{ checkin.tasting.name }}</td>
                </tr>
            {%  endfor %}
            </table>
                    <a href="/checkins/">View all checkins</a>
        {%  endif %}
    </div>
</div>
{%  endblock content %}

{% block script %}
{{ block.super }}
{% endblock script %}

tasting/templates/profile.html
{% extends 'base.html' %}

{%  block top %}
    Welcome {{ usr.first_name }}
    {{ block.super }}
{% endblock %}

{%  block menu %}
{%  endblock menu %}

{%  block content %}
    {% include 'profilemenu.html' %}

    {% if admin %}
        <h3>ADMIN stuff</h3>
        <a href="/imports/list_imports/">Imports</a><br>
    <hr>
    {%  if not logged_in %}
        <a href="{{ untappd_login_url }}">Connect to Untappd</a>
    {% else %}
        <span style="color: deeppink; font-weight: 900">
            Connected to untappd as <a href="https://untappd.com/user/{{ usr.taster.untappd_id }}">
            {{ usr.taster.untappd_id }}
        </a>
        </span><br>
        Latest untappd-checkins:<br>
        {%  if latest %}
            {% for l in latest %}
                {{ l.0 }} - {{ l.1 }}. Rating: {{ l.2 }} <br>
            {% endfor %}
        {% endif %}
    {% endif %}
    <hr>

    {% endif %}
    <h2>Your tastings</h2>
    {%  for tasting in tastings %}
        <a href="/tasting/{{ tasting.pk }}">
            {{ tasting.name }}
        </a> {% if tasting.finished %}
            ( Finished )
            <a href="/tasting/{{ tasting.pk }}/stats/"> Your stats</a> |
            <a href="/tasting/{{ tasting.pk }}/wrapitup/"> Overall stats</a>
    {% else %}
        starts at: {{ tasting.date|date:'d/m-y H:i' }}
    {% endif %}
        <br>
    {% endfor %}

    {%  if usr.taster.checkin_set.exists %}
        <h2>Your 10 latest checkins</h2>
        <table>
        <tr>
            <th>
                Beer
            </th>
            <th>
                Style
            </th>
            <th>
                Brewery
            </th>
            <th>
                Rating
            </th>
            <th>
                Date
            </th>
            <th>
                Tasting
            </th>
        </tr>
        {%  for checkin in checkins %}
            <tr>
            <td>
                <a href="/cellar/beer/{{ checkin.beer.pk }}">{{ checkin.beer.name }}</a>
            </td>
            <td>
                <a href="/cellar/style/{{ checkin.beer.style.pk }}">{{ checkin.beer.style.name }}</a>
            </td>
            <td>
                <a href="/cellar/brewery/{{ checkin.beer.brewery.pk }}">{{ checkin.beer.brewery }}</a>
            </td>
            <td>{{ checkin.overall }}</td>
            <td>{{ checkin.date|date:'d/m-y' }}</td>
            <td>{{ checkin.tasting.name }}</td>
            </tr>
        {%  endfor %}
        </table>
                <a href="/checkins/">View all checkins</a>
    {%  endif %}

{#    <h2>Dna favoriter</h2>#}
{#    <h3>Öl</h3>#}
{#    {%  for beer in usr.taster.beers %}#}
{#        {{ beer }}<br>#}
{#    {%  endfor %}#}
{##}
{#    <h3>Bryggerier</h3>#}
{#    {%  for brewery in usr.taster.breweries %}#}
{#        {{ brewery }}<br>#}
{#    {%  endfor %}#}
{##}
{#    <h3>Stilar</h3>#}
{#    {%  for style in usr.taster.styles %}#}
{#        {{ style }}<br>#}
{#    {%  endfor %}#}

{%  endblock content %}

tasting/templates/profilemenu.html
<div id="profile_menu">
    <table id="profile_menu">
        <tr>
            <th class="menuitem" id="beer_menu">
                BEERS
            </th>
            <th class="menuitem" id="tasting_menu">
                TASTINGS
            </th>
            <th class="menuitem" id="user_menu">
                <a href="/profile/">YOU</a>
            </th>

            <th class="menuitem" id="untappd_menu">
                UNTAPPD
            </th>
        </tr>

        <tr>
            <td colspan="4">
                <div class="submenu" id="beer_menu">
                    <span><a href="/cellar/beerfinder/">Beerfinder</a></span>
{#                    <span>Breweries</span>#}
{#                    <span>Styles</span>#}
{#                    <span>Countries</span>#}
                </div>

                <div class="submenu" id="user_menu">
                    <span><a href="/checkins/">Checkins</a></span>
                    <span>Find users</span>
                    <span>Friends</span>
                    <span>Favourite Beers</span>
                    <span>Favourite Breweries</span>
                    <span>Favourite Styles</span>
                    <span>Bottlesharing</span>
                </div>

                <div class="submenu" id="tasting_menu">
                    <span>Your tastings</span>
                    <span>Arrange tasting</span>
                </div>

                <div class="submenu" id="untappd_menu">
                    <span>Import friends</span>
                </div>

            </td>
        </tr>
    </table>
{#    <span class="menuitem">#}
{#        <a href="">USERS</a>#}
{#            <span class="submenu">Find user</span>#}
{#    </span>#}
{##}
{#    <span class="menuitem">#}
{#        <a href="">TASTINGS</a>#}
{#    </span>#}
{##}
{#    <span class="menuitem">#}
{#        <a href="">UNTAPPD</a>#}
{#        <span class="submenu">Checkins</span>#}
{#        <span class="submenu">Beers</span>#}
{#        <span class="submenu">Breweries</span>#}
{#        <span class="submenu">Styles</span>#}
{#        <span class="submenu">Countries</span>#}
{#    </span>#}
</div>

<script>


    $('.menuitem').hover(function(){
        $('.submenu').hide();
        var _id = $(this).attr('id');
        $('.submenu#' + _id).show();
    });

</script>

tasting/templates/stats_view.jinja2
<h2>{{ tasting }}</h2>
<hr>

{%  for beer in beers %}
    {{ beer }}<br>
{% endfor %}

<hr>
{%  for checkin in checkins %}
    {{ checkin }}<br>
{% endfor %}

<hr>